## CHANGE this to the name of your plugin.
name: CompressedMachines

## CHANGE this to your username.
author: Idra

## CHANGE this to a meaninful but short description of your plugin.
description: Adds compact variants of slimefun machines to boost server performance

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.idra.compressedmachines.CompressedMachines

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Idra/CompressedMachines

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14
